### ISSUE TITLE
thank you

### ISSUE THREAD

**Issue by trik57er** [EKapustin/align#2]
Hi! I ran the bat file from the Cadence parent folder, all messages reported about successful copied/installation but the "Align" function in the Edit didn't appear. Is it works for 17.2/17.4 Allegro or not?

**Comment by EKapustin** [comment]
I don't know, sorry. Try with allegro command line: aln

**Comment by dslake** [comment]
> Hi! I ran the bat file from the Cadence parent folder, all messages reported about successful copied/installation but the "Align" function in the Edit didn't appear. Is it works for 17.2/17.4 Allegro or not?

I also installed from bat file on a system with 17.2 and it didn't show up in Allegro. I found that I didn't have the %CDSROOT% environment variable set properly. Try setting it to the root of your Cadence install (where you see "share"). After I set the variable, it worked for me. 

It would be a nice enhancement to the installer if it checked the value of %CDSROOT% and printed it out, especially if it's not defined.
